# Generated by Django 3.2.6 on 2021-10-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzacart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='pizzacart/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
    ]
