# Generated by Django 3.2.6 on 2021-10-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzacart', '0004_product_piztype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='piztype',
            field=models.CharField(choices=[('Non-Veg', 'NON-VEG'), ('Veg', 'VEG')], default='', max_length=25),
        ),
    ]
