# Generated by Django 3.2.6 on 2021-10-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzacart', '0005_alter_product_piztype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(),
        ),
    ]
