# Generated by Django 3.2.6 on 2021-10-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzacart', '0006_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(default='', max_length=20),
        ),
    ]
