# Generated by Django 3.2.6 on 2021-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzacart', '0007_product_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('Square', 'Square'), ('Round', 'Round')], default='', max_length=20),
        ),
    ]
